on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "https://github.com/azerothcore/mod-random-enchants.git"
        source_branch: "master"
        destination_repo: "https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com/locus313/mod-random-enchants.git"
        destination_branch: "master"